# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: user_management.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class CreateUserRequest(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass
class CreateUserResponse(betterproto.Message):
    pass


@dataclass
class DeleteUserRequest(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass
class DeleteUserResponse(betterproto.Message):
    pass


class UserManagementServiceStub(betterproto.ServiceStub):
    async def create_user(self, *, id: str = "") -> CreateUserResponse:
        request = CreateUserRequest()
        request.id = id

        return await self._unary_unary(
            "/usermanagement.v1.UserManagementService/CreateUser",
            request,
            CreateUserResponse,
        )

    async def delete_user(self, *, id: str = "") -> DeleteUserResponse:
        request = DeleteUserRequest()
        request.id = id

        return await self._unary_unary(
            "/usermanagement.v1.UserManagementService/DeleteUser",
            request,
            DeleteUserResponse,
        )
